---
name: Elizaveta
surname: Kugaevskaia
position: "Ph.D. Candidate in International Public Policy. JSPS Research Fellow DC2."
address: "1-31 Machikaneyamacho, Toyonaka, Osaka, 560-0043, Japan"
orcid: "0009-0009-3584-598X"
www: "elisacoffee.github.io"
email: "kugaevskaya.elizaveta@gmail.com"
github: elisacoffee
twitter: elisainkyoto
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 309374
docname: CV
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

pacman::p_load(vitae, here, tidyverse,zoo)
```


# Education

```{r EDUCATION}
read.csv(here("data", "education.csv")) |>
  detailed_entries(
    with = degree,
    what = institution,
    why = details,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = location
  )
```

# Research

```{r}
research <- read.csv(here("data", "research.csv"))
```

## Working Papers

```{r}
research |>
  filter(type == "working_paper") |>
  detailed_entries(
    with = title,
    what = coauthors,
    why = details,
    where = date
  )
```

## Work in Progress

```{r}
research |>
  filter(type == "work_in_progress") |>
  detailed_entries(
    with = title,
    what = coauthors,
    why = details
  )
```

# Presentations

```{r}
presen <- read.csv(here("data", "presentations.csv")) |>
  mutate(date = paste0(month, " ", day, ", ", year),
         date = as.Date(date, format = "%B %e, %Y")) |>
  arrange(desc(date))
```

## Conferences
```{r CONFERENCE}
presen |>
  filter(type == "conference") |>
  detailed_entries(
    with = name,
    why = details,
    when = glue::glue("{month} {year}",.na = ""),
    where = location
  )
```

## Seminars
```{r SEMINAR}
presen |>
  filter(type == "seminar") |>
  detailed_entries(
    with = name,
    why = details,
    when = glue::glue("{month} {year}",.na = ""),
    where = location
  )
```

# Research Experience

```{r EMPLOYMENT}
read.csv(here("data", "work.csv")) |>
  detailed_entries(
    with = title,
    what = institution,
    why = details,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = "")
  )
```

# Teaching Experience

```{r TEACHING}
read.csv(here("data", "teaching.csv")) |>
  detailed_entries(
    with = glue::glue("{title}, {position}",.na = ""),
    what = glue::glue("{institution} ({level})",.na = ""),
    why = details,
    when = glue::glue("{semester} {year}",.na = ""),
    where = language
  )
```

# Other Experience

```{r OTHER}
read.csv(here("data", "other.csv")) |>
  detailed_entries(
    with = description,
    what = institution,
    why = details,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = language
  )
```

# Research Funding

```{r FUNDING}
read.csv(here("data", "funding.csv")) |>
  detailed_entries(
    with = organization,
    what = id,
    why = details,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = amount
  )
```

# Scholarships and Fellowships

```{r SCHOLARSHIPS}
read.csv(here("data", "scholarships.csv")) |>
  detailed_entries(
    with = name,
    why = details,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = "")
  )
```

# Honors and Awards

```{r HONORS}
read.csv(here("data", "honors.csv")) |>
  detailed_entries(
    with = name,
    what = organization,
    why = details,
    when = glue::glue("{month} {year}",.na = ""),
  )
```



# Skills

```{r SKILLS}
read.csv(here("data", "skills.csv")) |>
  detailed_entries(
    with = area,
    what = skills
  )
```