version: '3'
services:
    rstudio:
        build:
            context: .
        ports:
            - "8787:8787"
        volumes:
            - .:/home/rstudio/work
        restart: always
        tty: true
        stdin_open: true
        environment:
            - DISABLE_AUTH=true
            - TZ=Europe/Madrid